name: Release on Digitalocean droplet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build WAR with Maven
        run: mvn clean package -DskipTests

      - name: SCP the WAR to Droplet
        uses: appleboy/scp-action@v0.1.3  # Corrected version
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          source: target/*.war
          target: ${{ secrets.DEPLOY_PATH }}

      - name: SSH into Droplet and deploy WAR using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            sudo systemctl stop 2g.service || true
            sudo nohup java -jar rgsm-bot-0.1.1.war > log.txt 2>&1 &
            sudo systemctl start 2g.service